return {
	--{
	--	"nvim-telescope/telescope-ui-select.nvim",
	--},
	--{
	--	"nvim-telescope/telescope.nvim",
	--	tag = "0.1.5",
	--	dependencies = {
	--		"nvim-lua/plenary.nvim",
	--		"BurntSushi/ripgrep",
	--	},
	--	config = function()
	--		require("telescope").setup({
	--			extensions = {
	--				["ui-select"] = {
	--					require("telescope.themes").get_dropdown({}),
	--				},
	--			},
	--		})
	--		local builtin = require("telescope.builtin")
	--		vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "find files" })
	--		vim.keymap.set("n", "<leader>fi", function()
	--			require("telescope.builtin").find_files({ no_ignore = true, hidden = true })
	--		end, { desc = "find files including gitignore" })
	--		vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "live grep" })
	--		vim.keymap.set("n", "<leader>b", builtin.buffers, { desc = "list buffers" })
	--		vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "help tags" })
	--		require("telescope").load_extension("ui-select")
	--	end,
	--},
}
